<div class="wrap-ckfinder-multiple">
    <input type="text" {{ $attributes->class(['d-none']) }} name="{{ $name }}"
        value="{{ $marcoValue($value) }}">

    <div id="{{ $preview }}" class="gallery-container">
        @if ($value)
            @foreach ($value as $item)
                <div class="gallery-item" data-image="{{ asset($item) }}" data-index="{{ $loop->index }}">
                    <div class="gallery-item-wrapper">
                        <img src="{{ asset($item) }}" alt="Gallery Image" class="gallery-image">
                        <div class="gallery-overlay">
                            <div class="gallery-actions">
                                <span class="gallery-view-btn" title="Xem ảnh">
                                    <i class="ti ti-eye"></i>
                                </span>
                                <span class="delete-image-ckfinder" data-url="{{ $item }}" data-route="0"
                                    title="Xóa ảnh">
                                    <i class="ti ti-x"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        @endif
    </div>

    <div class="p-3">
        <button type="button" class="btn btn-primary add-image-ckfinder" data-preview="#{{ $preview }}"
            data-input="input[name='{{ $name }}']" data-type="MULTIPLE">
            <i class="ti ti-plus me-2"></i>{{ $btntext }}
        </button>
    </div>
</div>

<!-- Gallery Slider Modal -->
<div id="gallerySliderModal" class="gallery-modal">
    <div class="gallery-modal-content">
        <div class="gallery-modal-header">
            <h5 class="gallery-modal-title">Thư viện ảnh</h5>
            <span class="gallery-modal-close">&times;</span>
        </div>
        <div class="gallery-modal-body">
            <div class="gallery-slider-container">
                <button type="button" class="gallery-slider-btn gallery-slider-prev" id="galleryPrev">
                    <i class="ti ti-chevron-left"></i>
                </button>
                <div class="gallery-slider-main">
                    <img id="galleryMainImage" src="" alt="Gallery Image" class="gallery-main-image">
                </div>
                <button type="button" class="gallery-slider-btn gallery-slider-next" id="galleryNext">
                    <i class="ti ti-chevron-right"></i>
                </button>
            </div>
            <div class="gallery-slider-thumbnails" id="galleryThumbnails">
                <!-- Thumbnails will be generated by JavaScript -->
            </div>
        </div>
        <div class="gallery-modal-footer">
            <div class="gallery-counter">
                <span id="galleryCurrentIndex">1</span> / <span id="galleryTotalCount">1</span>
            </div>
        </div>
    </div>
</div>

<style>
    .gallery-container {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
        gap: 15px;
        margin-bottom: 20px;
        padding: 15px;
        background: #f8f9fa;
        border-radius: 8px;
        border: 2px dashed #dee2e6;
        min-height: 100px;
    }

    .gallery-item {
        position: relative;
        border-radius: 8px;
        overflow: hidden;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
        transition: all 0.3s ease;
    }

    .gallery-item.removing {
        opacity: 0;
        transform: scale(0.8);
        transition: all 0.3s ease;
    }

    .gallery-item.adding {
        opacity: 0;
        transform: scale(0.8);
        transition: all 0.3s ease;
    }

    .gallery-item.added {
        opacity: 1;
        transform: scale(1);
    }

    .gallery-item:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.15);
    }

    .gallery-item-wrapper {
        position: relative;
        width: 100%;
        height: 150px;
        overflow: hidden;
    }

    .gallery-image {
        width: 100%;
        height: 100%;
        object-fit: cover;
        transition: transform 0.3s ease;
    }

    .gallery-item:hover .gallery-image {
        transform: scale(1.05);
    }

    .gallery-overlay {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(0, 0, 0, 0.5);
        display: flex;
        align-items: center;
        justify-content: center;
        opacity: 0;
        transition: opacity 0.3s ease;
    }

    .gallery-item:hover .gallery-overlay {
        opacity: 1;
    }

    .gallery-actions {
        display: flex;
        gap: 10px;
        align-items: center;
        justify-content: center;
    }

    .gallery-view-btn {
        background: #28a745;
        color: white;
        width: 35px;
        height: 35px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        cursor: pointer;
        transition: all 0.3s ease;
        border: none;
        font-size: 16px;
    }

    .gallery-view-btn:hover {
        background: #218838;
        transform: scale(1.1);
    }

    .delete-image-ckfinder {
        background: #dc3545;
        color: white;
        width: 35px;
        height: 35px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        cursor: pointer;
        transition: all 0.3s ease;
        border: none;
        font-size: 16px;
        outline: none;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        user-select: none;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
    }

    .delete-image-ckfinder:focus {
        outline: none;
        box-shadow: 0 0 0 3px rgba(220, 53, 69, 0.3);
    }

    .delete-image-ckfinder:hover {
        background: #c82333;
        transform: scale(1.1);
    }

    .add-image-ckfinder {
        border: none;
        padding: 12px 24px;
        border-radius: 6px;
        font-weight: 500;
        transition: all 0.3s ease;
        box-shadow: 0 2px 4px rgba(0, 123, 255, 0.3);
        width: 100%;
        margin: 0;
    }

    .add-image-ckfinder:hover {
        transform: translateY(-1px);
        box-shadow: 0 4px 8px rgba(0, 123, 255, 0.4);
    }

    .gallery-container:empty::before {
        content: "Chưa có hình ảnh nào. Nhấn nút bên dưới để thêm ảnh.";
        display: flex;
        align-items: center;
        justify-content: center;
        color: #6c757d;
        font-style: italic;
        height: 100px;
        text-align: center;
    }

    @media (max-width: 768px) {
        .gallery-container {
            grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
            gap: 10px;
            padding: 10px;
        }

        .gallery-item-wrapper {
            height: 120px;
        }
    }

    /* Gallery Modal Styles */
    .gallery-modal {
        display: none;
        position: fixed;
        z-index: 9999;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.9);
        backdrop-filter: blur(5px);
        animation: fadeIn 0.3s ease;
    }

    .gallery-modal.show {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .gallery-modal-content {
        position: relative;
        background: white;
        border-radius: 12px;
        width: 90%;
        max-width: 1000px;
        max-height: 90vh;
        overflow: hidden;
        box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
        animation: slideIn 0.3s ease;
    }

    .gallery-modal-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px 25px;
        border-bottom: 1px solid #e9ecef;
        background: #f8f9fa;
    }

    .gallery-modal-title {
        margin: 0;
        font-size: 1.25rem;
        font-weight: 600;
        color: #333;
    }

    .gallery-modal-close {
        font-size: 28px;
        font-weight: bold;
        color: #aaa;
        cursor: pointer;
        transition: color 0.3s ease;
        line-height: 1;
    }

    .gallery-modal-close:hover {
        color: #000;
    }

    .gallery-modal-body {
        padding: 25px;
    }

    .gallery-slider-container {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        margin-bottom: 20px;
        background: #f8f9fa;
        border-radius: 8px;
        padding: 20px;
        min-height: 400px;
    }

    .gallery-slider-main {
        flex: 1;
        display: flex;
        align-items: center;
        justify-content: center;
        max-width: 600px;
    }

    .gallery-main-image {
        max-width: 100%;
        max-height: 400px;
        object-fit: contain;
        border-radius: 8px;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s ease;
    }

    .gallery-main-image:hover {
        transform: scale(1.02);
    }

    .gallery-slider-btn {
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
        background: rgba(0, 0, 0, 0.7);
        color: white;
        border: none;
        width: 50px;
        height: 50px;
        border-radius: 50%;
        cursor: pointer;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 20px;
        transition: all 0.3s ease;
        z-index: 10;
        outline: none;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
    }

    .gallery-slider-btn:focus {
        outline: none;
        box-shadow: 0 0 0 3px rgba(0, 123, 255, 0.3);
    }

    .gallery-slider-btn:hover {
        background: rgba(0, 0, 0, 0.9);
        transform: translateY(-50%) scale(1.1);
    }

    .gallery-slider-prev {
        left: 20px;
    }

    .gallery-slider-next {
        right: 20px;
    }

    .gallery-slider-thumbnails {
        display: flex;
        gap: 10px;
        justify-content: center;
        flex-wrap: wrap;
        max-height: 120px;
        overflow-y: auto;
    }

    .gallery-thumbnail {
        width: 80px;
        height: 80px;
        border-radius: 6px;
        overflow: hidden;
        cursor: pointer;
        border: 3px solid transparent;
        transition: all 0.3s ease;
        flex-shrink: 0;
    }

    .gallery-thumbnail img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .gallery-thumbnail.active {
        border-color: #007bff;
        box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.2);
    }

    .gallery-thumbnail:hover {
        border-color: #0056b3;
        transform: scale(1.05);
    }

    .gallery-modal-footer {
        padding: 15px 25px;
        border-top: 1px solid #e9ecef;
        background: #f8f9fa;
        text-align: center;
    }

    .gallery-counter {
        font-size: 14px;
        color: #6c757d;
        font-weight: 500;
    }

    @keyframes fadeIn {
        from {
            opacity: 0;
        }

        to {
            opacity: 1;
        }
    }

    @keyframes slideIn {
        from {
            opacity: 0;
            transform: scale(0.8) translateY(-50px);
        }

        to {
            opacity: 1;
            transform: scale(1) translateY(0);
        }
    }

    @media (max-width: 768px) {
        .gallery-modal-content {
            width: 95%;
            margin: 10px;
        }

        .gallery-slider-container {
            min-height: 300px;
            padding: 15px;
        }

        .gallery-main-image {
            max-height: 300px;
        }

        .gallery-slider-btn {
            width: 40px;
            height: 40px;
            font-size: 16px;
        }

        .gallery-slider-prev {
            left: 10px;
        }

        .gallery-slider-next {
            right: 10px;
        }

        .gallery-thumbnail {
            width: 60px;
            height: 60px;
        }
    }
</style>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Base URL helpers (respect meta url-home which may include app subdir like /CoreBanHang)
        function getBaseUrl() {
            const meta = document.querySelector('meta[name="url-home"]');
            return meta && meta.content ? meta.content.replace(/\/$/, '') : window.location.origin;
        }

        function normalizeFullUrl(pathOrUrl) {
            const origin = window.location.origin;
            const baseUrl = getBaseUrl();
            if (!pathOrUrl) return '';

            // Relative path -> prefix with baseUrl
            if (!/^https?:\/\//i.test(pathOrUrl)) {
                const p = pathOrUrl.replace(/^\//, '');
                return baseUrl + '/' + p;
            }

            // Full URL but missing app base path -> replace origin with baseUrl
            if (pathOrUrl.startsWith(origin) && !pathOrUrl.startsWith(baseUrl)) {
                return pathOrUrl.replace(origin, baseUrl);
            }
            return pathOrUrl;
        }
        const modal = document.getElementById('gallerySliderModal');
        const modalContent = modal.querySelector('.gallery-modal-content');
        const closeBtn = modal.querySelector('.gallery-modal-close');
        const mainImage = document.getElementById('galleryMainImage');
        const prevBtn = document.getElementById('galleryPrev');
        const nextBtn = document.getElementById('galleryNext');
        const thumbnailsContainer = document.getElementById('galleryThumbnails');
        const currentIndexSpan = document.getElementById('galleryCurrentIndex');
        const totalCountSpan = document.getElementById('galleryTotalCount');

        let currentIndex = 0;
        let images = [];
        let thumbnails = [];

        // Initialize gallery
        function initGallery() {
            const galleryItems = document.querySelectorAll('.gallery-item[data-image]');
            images = Array.from(galleryItems).map(item => ({
                src: item.dataset.image,
                index: parseInt(item.dataset.index)
            }));

            if (images.length === 0) return;

            totalCountSpan.textContent = images.length;
            generateThumbnails();

            // Add delete listeners for all delete buttons
            addDeleteListeners();

            // Ensure all existing items have proper styling
            galleryItems.forEach(item => {
                if (!item.classList.contains('added') && !item.classList.contains('adding')) {
                    item.classList.add('added');
                }
            });
        }

        // Generate thumbnails
        function generateThumbnails() {
            thumbnailsContainer.innerHTML = '';
            thumbnails = [];

            images.forEach((image, index) => {
                const thumbnail = document.createElement('div');
                thumbnail.className = 'gallery-thumbnail';
                if (index === 0) thumbnail.classList.add('active');

                const img = document.createElement('img');
                img.src = image.src;
                img.alt = `Thumbnail ${index + 1}`;

                thumbnail.appendChild(img);
                thumbnailsContainer.appendChild(thumbnail);
                thumbnails.push(thumbnail);

                thumbnail.addEventListener('click', () => goToSlide(index));
            });
        }

        // Open modal
        function openModal(index = 0) {
            if (images.length === 0) return;

            currentIndex = index;
            updateDisplay();
            modal.classList.add('show');
            document.body.style.overflow = 'hidden';
        }

        // Close modal
        function closeModal() {
            modal.classList.remove('show');
            document.body.style.overflow = '';
        }

        // Update display
        function updateDisplay() {
            if (images.length === 0) return;

            const currentImage = images[currentIndex];
            mainImage.src = currentImage.src;
            currentIndexSpan.textContent = currentIndex + 1;

            // Update thumbnails
            thumbnails.forEach((thumb, index) => {
                thumb.classList.toggle('active', index === currentIndex);
            });

            // Update navigation buttons
            prevBtn.style.display = images.length > 1 ? 'flex' : 'none';
            nextBtn.style.display = images.length > 1 ? 'flex' : 'none';
        }

        // Go to specific slide
        function goToSlide(index) {
            if (index < 0 || index >= images.length) return;
            currentIndex = index;
            updateDisplay();
        }

        // Next slide
        function nextSlide() {
            const nextIndex = (currentIndex + 1) % images.length;
            goToSlide(nextIndex);
        }

        // Previous slide
        function prevSlide() {
            const prevIndex = (currentIndex - 1 + images.length) % images.length;
            goToSlide(prevIndex);
        }

        // Event listeners
        closeBtn.addEventListener('click', closeModal);

        modal.addEventListener('click', function(e) {
            if (e.target === modal) {
                closeModal();
            }
        });

        prevBtn.addEventListener('click', prevSlide);
        nextBtn.addEventListener('click', nextSlide);

        // Keyboard navigation
        document.addEventListener('keydown', function(e) {
            if (!modal.classList.contains('show')) return;

            switch (e.key) {
                case 'Escape':
                    closeModal();
                    break;
                case 'ArrowLeft':
                    prevSlide();
                    break;
                case 'ArrowRight':
                    nextSlide();
                    break;
            }
        });

        // Touch/swipe support for mobile
        let startX = 0;
        let startY = 0;

        modalContent.addEventListener('touchstart', function(e) {
            startX = e.touches[0].clientX;
            startY = e.touches[0].clientY;
        });

        modalContent.addEventListener('touchend', function(e) {
            if (!startX || !startY) return;

            const endX = e.changedTouches[0].clientX;
            const endY = e.changedTouches[0].clientY;

            const diffX = startX - endX;
            const diffY = startY - endY;

            // Only trigger if horizontal swipe is more significant than vertical
            if (Math.abs(diffX) > Math.abs(diffY) && Math.abs(diffX) > 50) {
                if (diffX > 0) {
                    nextSlide(); // Swipe left - next image
                } else {
                    prevSlide(); // Swipe right - previous image
                }
            }

            startX = 0;
            startY = 0;
        });

        // Add click listeners to gallery items
        document.addEventListener('click', function(e) {
            if (e.target.closest('.gallery-view-btn')) {
                const galleryItem = e.target.closest('.gallery-item');
                const index = parseInt(galleryItem.dataset.index);
                openModal(index);
            }

            // Handle delete button click
            if (e.target.closest('.delete-image-ckfinder')) {
                e.preventDefault();
                e.stopPropagation();
                e.stopImmediatePropagation();

                const deleteBtn = e.target.closest('.delete-image-ckfinder');
                const galleryItem = deleteBtn.closest('.gallery-item');
                const imageUrl = deleteBtn.dataset.url;

                // Remove image immediately without any confirmation
                removeImageFromGallery(galleryItem, imageUrl);

                return false;
            }
        });

        // Also add direct event listeners for delete buttons
        function addDeleteListeners() {
            const deleteButtons = document.querySelectorAll('.delete-image-ckfinder');
            deleteButtons.forEach(btn => {
                // Remove existing listeners to avoid duplicates
                btn.removeEventListener('click', handleDeleteClick);
                btn.addEventListener('click', handleDeleteClick);
            });
        }

        function handleDeleteClick(e) {
            e.preventDefault();
            e.stopPropagation();
            e.stopImmediatePropagation();

            const deleteBtn = e.currentTarget;
            const galleryItem = deleteBtn.closest('.gallery-item');
            const imageUrl = deleteBtn.dataset.url;
            const fullImageUrl = galleryItem.dataset.image; // Full URL for modal check

            console.log('Delete button clicked:', imageUrl); // Debug log

            // Remove image immediately without any confirmation
            removeImageFromGallery(galleryItem, fullImageUrl);

            return false;
        }

        // Function to remove image from gallery
        function removeImageFromGallery(galleryItem, imageUrl) {
            if (!galleryItem) return;

            console.log('Removing image:', imageUrl); // Debug log

            // Add removing animation class
            galleryItem.classList.add('removing');

            // Remove from DOM after animation
            setTimeout(() => {
                if (galleryItem && galleryItem.parentNode) {
                    galleryItem.remove();
                    console.log('Image removed from DOM'); // Debug log
                }

                // Update hidden input value
                updateHiddenInput();

                // Re-initialize gallery
                initGallery();
            }, 300); // Match CSS transition duration

            // Close modal if it's open and showing the deleted image
            if (modal && modal.classList.contains('show')) {
                const currentImageSrc = mainImage ? mainImage.src : '';
                if (currentImageSrc && currentImageSrc.includes(imageUrl)) {
                    closeModal();
                }
            }
        }

        // Function to update hidden input value
        function updateHiddenInput() {
            const hiddenInput = document.querySelector('input[name="{{ $name }}"]');
            if (!hiddenInput) return;

            const remainingImages = Array.from(document.querySelectorAll('.gallery-item[data-image]'))
                .map(item => {
                    // Get the relative path from data-url attribute (like in edit mode)
                    const deleteBtn = item.querySelector('.delete-image-ckfinder');
                    if (deleteBtn && deleteBtn.dataset.url) {
                        return deleteBtn.dataset.url;
                    }

                    // Fallback: convert data-image to relative path
                    const baseUrl = getBaseUrl();
                    let imagePath = item.dataset.image;
                    if (imagePath.startsWith('http')) {
                        imagePath = imagePath.replace(baseUrl, '');
                        imagePath = imagePath.replace(window.location.origin, '');
                    }
                    if (imagePath.startsWith('/')) {
                        imagePath = imagePath.substring(1);
                    }
                    return imagePath;
                });

            hiddenInput.value = remainingImages.join(',');
        }

        // Load images from hidden input on initialization
        function loadImagesFromInput() {
            const hiddenInput = document.querySelector('input[name="{{ $name }}"]');
            if (!hiddenInput || !hiddenInput.value) return;

            try {
                // Try JSON first (for backward compatibility)
                const imageArray = JSON.parse(hiddenInput.value);
                if (Array.isArray(imageArray) && imageArray.length > 0) {
                    const galleryContainer = document.getElementById('{{ $preview }}');
                    galleryContainer.innerHTML = '';
                    imageArray.forEach((imagePath, index) => {
                        if (imagePath && imagePath.trim() !== '') {
                            let fullImageUrl = normalizeFullUrl(imagePath);
                            addImageToGallery(fullImageUrl, index);
                        }
                    });
                    return;
                }
            } catch (e) {
                // Not JSON, treat as comma-separated string
            }

            // Handle comma-separated string
            const imageString = hiddenInput.value;
            if (imageString && imageString.trim() !== '') {
                const imageArray = imageString.split(',').map(item => item.trim()).filter(item => item !== '');
                if (imageArray.length > 0) {
                    const galleryContainer = document.getElementById('{{ $preview }}');
                    galleryContainer.innerHTML = '';
                    imageArray.forEach((imagePath, index) => {
                        let fullImageUrl = normalizeFullUrl(imagePath);
                        addImageToGallery(fullImageUrl, index);
                    });
                }
            }
        }

        // Initialize when DOM is ready
        loadImagesFromInput();
        initGallery();

        // Function to add new image to gallery
        function addImageToGallery(imageSrc, imageIndex) {
            const galleryContainer = document.getElementById('{{ $preview }}');
            if (!galleryContainer) return;

            // Convert full URL to relative path for data-url (like in edit mode)
            const baseUrl = getBaseUrl();
            imageSrc = normalizeFullUrl(imageSrc);
            let relativePath = imageSrc;
            if (/^https?:\/\//i.test(imageSrc)) {
                relativePath = imageSrc.replace(baseUrl, '');
                relativePath = relativePath.replace(window.location.origin, '');
            }
            if (relativePath.startsWith('/')) {
                relativePath = relativePath.substring(1);
            }

            // Create new gallery item with proper structure (exactly like edit mode)
            const galleryItem = document.createElement('div');
            galleryItem.className = 'gallery-item';
            galleryItem.setAttribute('data-image', imageSrc); // Full URL for display
            galleryItem.setAttribute('data-index', imageIndex);

            // Create wrapper
            const wrapper = document.createElement('div');
            wrapper.className = 'gallery-item-wrapper';

            // Create image
            const img = document.createElement('img');
            img.src = imageSrc;
            img.alt = 'Gallery Image';
            img.className = 'gallery-image';

            // Create overlay
            const overlay = document.createElement('div');
            overlay.className = 'gallery-overlay';

            // Create actions
            const actions = document.createElement('div');
            actions.className = 'gallery-actions';

            // Create view button
            const viewBtn = document.createElement('span');
            viewBtn.className = 'gallery-view-btn';
            viewBtn.title = 'Xem ảnh';
            viewBtn.innerHTML = '<i class="ti ti-eye"></i>';

            // Create delete button
            const deleteBtn = document.createElement('span');
            deleteBtn.className = 'delete-image-ckfinder';
            deleteBtn.setAttribute('data-url', relativePath);
            deleteBtn.setAttribute('data-route', '0');
            deleteBtn.title = 'Xóa ảnh';
            deleteBtn.innerHTML = '<i class="ti ti-x"></i>';

            // Assemble the structure
            actions.appendChild(viewBtn);
            actions.appendChild(deleteBtn);
            overlay.appendChild(actions);
            wrapper.appendChild(img);
            wrapper.appendChild(overlay);
            galleryItem.appendChild(wrapper);

            // Add to container
            galleryContainer.appendChild(galleryItem);

            // Add animation for new item
            galleryItem.classList.add('adding');
            setTimeout(() => {
                galleryItem.classList.remove('adding');
                galleryItem.classList.add('added');
            }, 10);

            // Update hidden input
            updateHiddenInput();

            // Re-initialize gallery
            initGallery();

            // Add delete listener for the new image
            deleteBtn.addEventListener('click', handleDeleteClick);
        }

        // Override CKFinder callback to add images properly
        window.addImageToGallery = addImageToGallery;

        // Re-initialize when new images are added (for dynamic content)
        const observer = new MutationObserver(function(mutations) {
            mutations.forEach(function(mutation) {
                if (mutation.type === 'childList') {
                    const addedNodes = Array.from(mutation.addedNodes);
                    const hasNewGalleryItems = addedNodes.some(node =>
                        node.nodeType === 1 && node.classList && node.classList.contains(
                            'gallery-item')
                    );

                    if (hasNewGalleryItems) {
                        // Small delay to ensure DOM is fully updated
                        setTimeout(() => {
                            initGallery();
                        }, 100);
                    }
                }
            });
        });

        const galleryContainer = document.getElementById('{{ $preview }}');
        if (galleryContainer) {
            observer.observe(galleryContainer, {
                childList: true,
                subtree: true
            });
        }

        // Intercept add button for THIS gallery and open CKFinder directly
        function setupCKFinderListener() {
            const previewSelector = '#{{ $preview }}';

            document.addEventListener('click', function(e) {
                const btn = e.target.closest('.add-image-ckfinder');
                if (!btn) return;
                const btnPreview = btn.getAttribute('data-preview');
                const btnType = btn.getAttribute('data-type');
                const inputSelector = btn.getAttribute('data-input');
                if (btnPreview !== previewSelector || btnType !== 'MULTIPLE') return;

                e.preventDefault();
                e.stopPropagation();
                e.stopImmediatePropagation();

                const urlHome = getBaseUrl();

                if (window.CKFinder && typeof window.CKFinder.popup === 'function') {
                    window.CKFinder.popup({
                        chooseFiles: true,
                        width: 800,
                        height: 600,
                        onInit: function(finder) {
                            finder.on('files:choose', function(evt) {
                                const files = evt.data.files;
                                const hiddenInput = document.querySelector(
                                    inputSelector);
                                let currentValue = hiddenInput && hiddenInput
                                    .value ? hiddenInput.value : '';
                                let valueArray = [];
                                // Parse current value (comma-separated string)
                                if (currentValue && currentValue.trim() !== '') {
                                    valueArray = currentValue.split(',').map(
                                        function(p) {
                                            return p.trim();
                                        }).filter(Boolean);
                                }

                                files.forEach(function(file, index) {
                                    let imageSrc = file.getUrl();
                                    imageSrc = normalizeFullUrl(imageSrc);

                                    // Relative path to store
                                    let relativePath = imageSrc.replace(
                                        urlHome, '').replace(window
                                        .location.origin, '');
                                    relativePath = relativePath.replace(
                                        /^\//, '');

                                    // Update input and UI
                                    valueArray.push(relativePath);
                                    const currentImages = document
                                        .querySelectorAll(
                                            '.gallery-item[data-image]');
                                    const imageIndex = currentImages
                                        .length + index;
                                    addImageToGallery(imageSrc, imageIndex);
                                });

                                if (hiddenInput) hiddenInput.value = valueArray
                                    .join(',');
                            });
                        }
                    });
                }
            }, true);
        }

        // Setup CKFinder listener
        setupCKFinderListener();

        // Also listen for input changes (fallback)
        const hiddenInput = document.querySelector('input[name="{{ $name }}"]');
        if (hiddenInput) {
            hiddenInput.addEventListener('change', function() {
                // Small delay to ensure CKFinder has processed the files
                setTimeout(() => {
                    initGallery();
                }, 200);
            });
        }
    });
</script>
